name: CICD

on:
  push:
    branches: [deploy to ec2]

jobs:
  build:
    runs-on: [ubuntu:latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Build docker image
        run: docker build -t vijayalakshminaga/nodejs-app .
      - name: Publish image to docker hub
        run: docker push vijayalakshminaga/nodejs-app:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from dockerhub
        run: docker pull vijayalakshminaga/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container vijayalakshminaga/nodejs-app           